plugins:
  - rubocop-rake

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - "test/**/*"

Naming/PredicateMethod:
  AllowedMethods:
    - try_put
